module.exports = {
	js: {
		options: {
			banner: '/*!DO NOT CHANGE THIS FILE MANUALLY -- generated by grunt',
		},
		src:[
            'bower_components/jquery/dist/jquery.js',
            'bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.js',
            'bower_components/modernizr/modernizr.js',

            'app/assets/scripts/funcs.js',
            'app/assets/scripts/main.js',
			'app/assets/scripts/header.js',
			'app/assets/scripts/footer.js',
            'app/assets/scripts/alert.js',
            'app/assets/scripts/ddl.js',
            'app/assets/scripts/sidemenu.js',
            'app/assets/scripts/sidenavigation.js'
			//place your Scripts files here
		],

		dest: 'dev-build/assets/scripts/scripts.js'
	}
};