module.exports = {
  
  options: {
      banner: '/*!DO NOT CHANGE THIS FILE MANUALLY -- generated by grunt'
  },

  dist: {
    files: {
      'public-build/scripts/app.min.js': ['.temp/javascripts/scripts.js']
    }
  }

};